apiVersion: v1
kind: Namespace
metadata:
  name: kagent
---
# apiVersion: source.toolkit.fluxcd.io/v1
# kind: OCIRepository
# metadata:
#   name: kagent
#   namespace: flux-system
# spec:
#   interval: 1h
#   url: oci://ghcr.io/kagent-dev/kagent/helm/kagent
#   ref:
#     tag: "0.9.4"

# Switching to HelmRepository as OCIRepository has an issue with deployment,
# specifically it gets wrong version
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kagent
  namespace: flux-system
spec:
  interval: 5m
  type: oci
  url: oci://ghcr.io/kagent-dev/kagent/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent
  namespace: kagent
spec:
  chart:
    spec:
      interval: 1h
      chart: kagent
      version: 0.9.4
      sourceRef:
        kind: HelmRepository
        name: kagent
        namespace: flux-system
  interval: 1m
  releaseName: kagent
  dependsOn:
  - name: kagent-crds
    namespace: kagent
  install:
    createNamespace: true
  values:
    tag: 0.9.4
    controller:
      image:
        tag: 0.9.4
    ui:
      image:
        tag: 0.9.4
    argo-rollouts-agent:
      enabled: false
    cilium-policy-agent:
      enabled: false
    cilium-manager-agent:
      enabled: false
    cilium-debug-agent:
      enabled: false
    istio-agent:
      enabled: false
    querydoc:
      enabled: false
    providers:
      default: gemini
      #openAI:
      #  apiKey: OPENAI_API_KEY_STUB
      gemini:
        provider: Gemini
        model: gemini-2.5-flash # gemini-2.5-flash-lite
        #apiKeySecretRef: kagent-gemini
        #apiKeySecretKey: GOOGLE_API_KEY
        apiKey: GOOGLE_API_KEY_STUB

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kagent
  namespace: kagent
spec:
  parentRefs:
  - name: agentgateway-external
    namespace: agentgateway-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: kagent-ui
      namespace: kagent
      port: 8080
