apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agentgateway.yaml
  - kagent.yaml

  # Extra tools and agents
  - mcp-server.yaml
  - kagent-models.yaml
  - kagent-k8s-read.yaml
